GET http://localhost:8080/flowers

POST http://localhost:8080/flowers
Content-Type: application/json

{
  "flowertype": "Rose",
  "flowercolor": "Red",
  "price": 25.50,
  "availible": true
}

GET http://localhost:8080/user

POST http://localhost:8080/user
Content-Type: application/json

{
  "email": "test@example.com",
  "dob": "2000-01-01"
}

GET http://localhost:8080/user/email?email=test@example.com